jtheme: page-themes/midnight@v0.2.0
title: Homepage of Fred Drueck
description: IT Professional
show_downloads: false
plugins:
- jekyll-remote-theme

navigation:
  - name: Top
    link: /

  - name: Accessibility Notes for UIC Red
    link: ./red-accessiblity/
